#!/bin/bash
# AUTOBOT API Key Rotation Script
# Usage: ./api_rotation_guide.sh

echo "=========================================="
echo "AUTOBOT API KEY ROTATION GUIDE"
echo "=========================================="
echo ""
echo "STEP 1: Generate New API Keys on Binance"
echo "----------------------------------------"
echo "1. Go to: https://www.binance.com/en/my/settings/api-management"
echo "2. Create new API key with:"
echo "   - Enable Futures: ✓"
echo "   - Enable Spot: (optional)"
echo "   - Enable Reading: ✓"
echo "   - Enable Spot & Margin Trading: ✓"
echo "   - IP Restriction: Add this server IP"
echo ""
echo "STEP 2: Get Telegram Bot Token"
echo "----------------------------------------"
echo "1. Message @BotFather on Telegram"
echo "2. Send: /newbot"
echo "3. Follow instructions to get token"
echo ""
echo "STEP 3: Update .env File"
echo "----------------------------------------"
echo "Replace the following values in /root/autobot_system/.env:"
echo ""
echo "BINANCE_API_KEY=<your_new_api_key>"
echo "BINANCE_API_SECRET=<your_new_api_secret>"
echo "TELEGRAM_BOT_TOKEN=<your_new_bot_token>"
echo ""
echo "STEP 4: Test New Credentials"
echo "----------------------------------------"
echo "Run: python3 -c \"
\"from config.settings import settings; \\
print('API Key:', settings.binance_api_key[:10] + '...'); \\
print('Telegram Token:', settings.telegram_bot_token[:10] + '...')\""
echo ""
echo "=========================================="
echo "NOTES:"
echo "- Testnet keys are currently in use"
echo "- For PRODUCTION, use live keys from fapi.binance.com"
echo "- Always keep backup of old keys until verified"
echo "=========================================="
